### ISSUE TITLE
vm gzip error

### ISSUE THREAD

**Issue by PDX4N6** [gyf304/vmcli#14]
I continue to get the following error:

❯ sudo make build/vm/ubuntu
mkdir -p build
mkdir -p build/vm
mkdir -p build/vm/ubuntu
cd build/vm/ubuntu && ../../../vmbuilders/ubuntu.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.1M  100 11.1M    0     0  3169k      0  0:00:03  0:00:03 --:--:-- 3168k
gunzip: vmlinux.gz: not in gzip format
make: *** [build/vm/ubuntu] Error 1

**Comment by gyf304** [comment]
Apparently, for x86_64, the vmlinux image is not gzip-compressed, but self-extracted. Fixed in the latest commit.

**Comment by gyf304** [comment]
Feel free to reopen if you encounter other issues.
