### ISSUE TITLE
How to make a connection between two guest VMs?

### ISSUE THREAD

**Issue by ChangheeOh** [gyf304/vmcli#18]
I have create two guest VMs(w1, w2)and can ssh into both of them from the host Mac.
But I can't ping or anything from w1 to w2 or from w2 to w1.
Please someone help me to resolve this issue.

Network configuration
- Host Mac: 192.168.64.1
- w1: 192.168.64.8
- w2: 192.168.64.9

Ping test result
- Success: host Mac -> w1, w2
- Success: w1, w2 -> host Mac
- Fail: w1 -> w2 (Destination Host Unreachable)
- Fail: w2 -> w1 (Destination Host Unreachable)

HTTP test result (via curl)
- Success: host Mac -> w1, w2
- Success: w1, w2 -> host Mac
- Fail: w1 -> w2, w2 -> w1
- Success: w1 -> w1, w2 -> w2

**Comment by gyf304** [comment]
This is currently a limitation of Apple. You can workaround it by setting up a VPN server on your Mac, and connect your VMs to the VPN. (I recommend Wireguard for this)

**Comment by ChangheeOh** [comment]
@gyf304 Thanks for your advices.
