### ISSUE TITLE
Debian doesn't boot properly or console input doesn't work

### ISSUE THREAD

**Issue by tiehfood** [gyf304/vmcli#21]
When trying to boot a Debian 10.8 installation, boot process got stuck (picture below).
MacBook Pro 2020, M1
Debian 10.8
Linux-Kernel 4

vmcli --kernel=linux --initrd=initrd --cpu-count=4 --memory-size=3072 --disk=disk.img --cmdline='console=tty0 console=hvc0 root=/dev/mapper/vm--vg-root ro apparmor=0' --network=nat
<img width="505" alt="image" src="https://user-images.githubusercontent.com/22456525/122557733-79348680-d03d-11eb-8162-e8d76d0fda32.png">

**Comment by gyf304** [comment]
One thing I can think of is that Getty is started on tty1 instead of hvc0. If Getty is not started on the correct tty, you won't get login prompt.

**Comment by tiehfood** [comment]
How could I change this?

**Comment by tiehfood** [comment]
I dont't know which one fixed it, but I did:
* added `virtio_console`to /etc/initramfs-tools/modules (update-initramfs -u)
* systemctl enable serial-getty@hvc0
