### ISSUE TITLE
Virtualization.framework is crashing on start

### ISSUE THREAD

**Issue by florin-pop** [gyf304/vmcli#30]
I followed the README on a MacBook Air M1 in order to start an `ubuntu` VM.
Nothing was printed after executing `vmctl start ubuntu` and `vmctl attach ubuntu` was not able to find a screen.
A new crash report was created with the information:

```
Generic Platform
FIXME: "Unhandled system register S3_0_C0_C6_2"
```

I am running `macOS 12.2.1`

**Comment by florin-pop** [comment]
[com.apple.Virtualization.VirtualMachine-2022-03-11-183856.ips.zip](https://github.com/gyf304/vmcli/files/8234262/com.apple.Virtualization.VirtualMachine-2022-03-11-183856.ips.zip)

**Comment by florin-pop** [comment]
It looks like it's caused by a faulty VM creation 🤔 
I created the VM with the script from https://github.com/evansm7/vftool and starting it using `vmctl` worked

**Comment by apinske** [comment]
https://github.com/apinske/virt/commit/8af935873ac3641c513fb4df96e6c0b850b5b78d

**Comment by florin-pop** [comment]
Confirmed, it's working as expected in `macOS 12.3`
