### ISSUE TITLE
VZBridgedNetworkDeviceAttachment网卡添加失败

### ISSUE THREAD

**Issue by darvintang** [gyf304/vmcli#35]
不能添加桥接网卡

**Comment by gyf304** [comment]
Hi, @darvintang , thank you for your interest in vmcli. The use of `VZBridgedNetworkDeviceAttachment` is restricted by the `com.apple.vm.networking` entitlement. Apple only issues this entitlement to VM software developers. Unfortunately without such a developer account, one would not be able to build vmcli with this ability.
See [com.apple.vm.networking](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_vm_networking?language=objc)

Hope this answers your question.

你好 @darvintang ，使用 `VZBridgedNetworkDeviceAttachment` 需要 `com.apple.vm.networking` 资格。Apple 仅会给虚拟机软件开发者提供此资格。没有有这个资格的开发者账号无法编译有此功能的 vmcli。
参看 [com.apple.vm.networking](https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_vm_networking?language=objc)

希望这个回答能帮到您。
