### ISSUE TITLE
Unable to compile - seems to require Xcode.app

### ISSUE THREAD

**Issue by hbokh** [gyf304/vmcli#4]
Hi! I am unable to compile with only the Xcode command line tools installed:
```
$ make
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
xcodebuild -project vmcli.xcodeproj -scheme vmcli -configuration Release
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
make: *** [build/vmcli] Error 1
```

Do we need the big Xcode.app installed too?

Since I'm still on macOS 10.14.6 "Mojave", I don't think it's going to work at all.
So maybe add a requirement, just as [`vftool`](https://github.com/evansm7/vftool) states: "Requires macOS >= 11."

**Comment by gyf304** [comment]
We do need the XCode.app installed. macOS 11+ is also a requirement. Both prerequisites are now added to README.md. Thanks for the feedback!
