### ISSUE TITLE
Unable to start VM with networking

### ISSUE THREAD

**Issue by SimonTate** [gyf304/vmcli#5]
Hi,

Firstly, thanks for this project. Extremely useful. 😄 

I have noticed an issue, and found the root cause, but I'd like to discuss the direction of any PR.

### The issue:

When running `vmcli` on main with the networking portion left in, the VM never starts and _silently_ fails. If I remove the networking code, then `vmcli` starts the VM with no issues (except no networking, obviously).

Debugging this, found the following log in console: `default	08:55:10.482714+0000	InternetSharing	VMNet in NAT mode can't be started now due to an active InternetSharing session on en0`.

### The fix:

Disable InternetSharing. Simple as that. Then everything works as expected (with a NAT device, haven't tested bridge mode).

How should we "fix" this? A note in documentation? Or a check in the code for this scenario (if possible?)?

**Comment by gyf304** [comment]
I added a print to stderr if the VM fails to start, hope that will make things easier to debug. Also added a note for InternetSharing in README.md.
Thank you for your feedback!

**Comment by SimonTate** [comment]
Looks great. Thanks!
